/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'about-section': AboutSection;
    'buy-ticket-section': BuyTicketSection;
    'contact-section': ContactSection;
    'cta-section': CtaSection;
    'event-tracks-section': EventTracksSection;
    'features-section': FeaturesSection;
    'partners-section': PartnersSection;
    'speakers-section': SpeakersSection;
    'visitors-info-section': VisitorsInfoSection;
    'why-tallinn-section': WhyTallinnSection;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
  };
  login: {
    password: string;
    email: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: number;
  title: string;
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buy-ticket-section".
 */
export interface BuyTicketSection {
  id: number;
  title: string;
  ticketUrl: string;
  ticketOptions?:
    | {
        title: string;
        description: string;
        price: number;
        included: {
          included: string;
          id?: string | null;
        }[];
        notIncluded?:
          | {
              notIncluded?: string | null;
              id?: string | null;
            }[]
          | null;
        isFeatured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  title: string;
  targetMail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-section".
 */
export interface CtaSection {
  id: number;
  title?: string | null;
  description: string;
  button: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-tracks-section".
 */
export interface EventTracksSection {
  id: number;
  day1: {
    hourStart?: string | null;
    hourEnd?: string | null;
    title: string;
    location?: string | null;
    id?: string | null;
  }[];
  day2: {
    hourStart: string;
    hourEnd: string;
    title: string;
    location?: string | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-section".
 */
export interface FeaturesSection {
  id: number;
  features: {
    title?: string | null;
    keyTopics?:
      | {
          topic?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-section".
 */
export interface PartnersSection {
  id: number;
  title: string;
  partners: {
    name: string;
    image: number | Media;
    url?: string | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers-section".
 */
export interface SpeakersSection {
  id: number;
  title: string;
  speakers: {
    name?: string | null;
    position?: string | null;
    image?: number | Media | null;
    linkedinUrl?: string | null;
    xUrl?: string | null;
    isDisclosed: boolean;
    bio?: string | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors-info-section".
 */
export interface VisitorsInfoSection {
  id: number;
  title: string;
  howToGetThere: {
    title: string;
    content: string;
  };
  nearbyHotels: {
    title: string;
    content: {
      title: string;
      description: string;
      link: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-tallinn-section".
 */
export interface WhyTallinnSection {
  id: number;
  title: string;
  reasons: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}